vendor: Blood Orange
name: Bundle Bar
version: 20211123-live
website_url: https://bundle.bar/
documentation_url: https://bundle.bar/docs/
product_logo_url: https://bloodorange.io/images/bundlebar.png
type: hosted
description: The registry for small stuff
